model:
  version: "md"
  encoder:
    d_model: 512
    num_heads: 8
    num_layers: 6
    ffn_dim: 2048
    conv_kernel: 31
    dropout: 0.1

  decoder:
    d_model: 512
    num_heads: 8
    num_layers: 6
    ffn_dim: 2048
    dropout: 0.1
