dataset:
  path: dataset
  workers: 16
  window_ms: 8000
  overlap: 0.9
  split:
    train: 0.8
    val: 0.2
  map_filters:
    sr_min: 0
    sr_max: 11
    variable_bpm: false
    tokenizer_limits: true

cache:
  path: cache

checkpoint:
  path: checkpoints

audio:
  sample_rate: 22050
  hop_ms: 10
  win_ms: 25
  n_mels: 80
  n_fft: 1024

tokenizer:
  DT_BIN_MS: 10
  X_BINS: 32
  Y_BINS: 24
  SLIDER_CP_LIMIT: 9
  SLIDER_VEL_LIMIT: 5
  BPM_MIN: 40
  BPM_MAX: 300
  BPM_JUMP: 5
  SLIDER_LEN_BINS: 10
  SLIDER_LEN_MAX: 1000

model:
  encoder:
    d_model: 768
    layers: 14
    heads: 12
    ffn_dim: 3072
    conv_kernel: 31
    dropout: 0.1

  decoder:
    d_model: 768
    layers: 10
    heads: 12
    ffn_dim: 3072
    dropout: 0.1

training:
  batch_size: 16
  use_ram: true
  workers: 4
  epochs: 100
  lr: 0.0001
  lr_scheduler: # reduce_on_plateau
    factor: 0.5
    patience: 2
    threshold: 1e-4
    min_lr: 1e-6
  early_stop:
    patience: 10
    delta: 0.0001