dataset:
  path: dataset

cache:
  path: cache

tokenizer:
  DT_BIN_MS: 10
  X_BINS: 32
  Y_BINS: 24
  SLIDER_CP_LIMIT: 9
  SLIDER_VEL_LIMIT: 5
  BPM_MIN: 40
  BPM_MAX: 300
  BPM_JUMP: 5
  SLIDER_LEN_BINS: 10
  SLIDER_LEN_MAX: 1000

model:
  encoder:
    d_model: 768
    layers: 14
    heads: 12
    ffn_dim: 3072
    conv_kernel: 31
    dropout: 0.1

  decoder:
    d_model: 768
    layers: 10
    heads: 12
    ffn_dim: 3072
    dropout: 0.1