DESCRIPTOR_TAGS: tuple[str, ...] = (
    "additions/custom skin",
    "additions/keysounds",
    "context/custom song",
    "context/mapping contest",
    "context/tournament custom",
    "expression/chaotic",
    "expression/conceptual",
    "expression/difficulty spike",
    "expression/high contrast",
    "expression/improvisation",
    "expression/inspo",
    "expression/iNiS-style",
    "expression/old-style revival",
    "expression/playfield usage",
    "expression/progression",
    "expression/repetition",
    "expression/simple",
    "gimmick/2B",
    "gimmick/aspire",
    "gimmick/circle only",
    "gimmick/memory",
    "gimmick/ninja spinners",
    "gimmick/playfield constraint",
    "gimmick/slider only",
    "gimmick/storyboard",
    "gimmick/video",
    "jumps/back and forth",
    "jumps/cross-screen",
    "jumps/freeform",
    "jumps/linear",
    "jumps/sharp",
    "jumps/spaced jumps",
    "jumps/squares",
    "jumps/stamina",
    "jumps/stars",
    "jumps/triangles",
    "jumps/wide",
    "meta/accelerating bpm",
    "meta/collab",
    "meta/mega collab",
    "meta/multi-song",
    "meta/swing",
    "meta/time signatures",
    "meta/variable timing",
    "reading/overlaps",
    "reading/perfect stacks",
    "reading/visually dense",
    "skillset/alt",
    "skillset/gimmick",
    "skillset/jumps",
    "skillset/precision",
    "skillset/reading",
    "skillset/streams",
    "skillset/tech",
    "sliders/complex slidershapes",
    "sliders/complex sv",
    "sliders/high sv",
    "sliders/low sv",
    "streams/bursts",
    "streams/cutstreams",
    "streams/flow aim",
    "streams/spaced streams",
    "streams/speed",
    "streams/stamina",
    "style/avant-garde",
    "style/clean",
    "style/distance snap",
    "style/freeform",
    "style/geometric",
    "style/grid snap",
    "style/hexgrid",
    "style/messy",
    "style/symmetrical",
)


DESCRIPTOR_TO_INDEX: dict[str, int] = {name: idx for idx, name in enumerate(DESCRIPTOR_TAGS)}
