from typing import Literal


StyleTag = Literal[
    "additions/keysounds",
    "expression/chaotic",
    "expression/playfield usage",
    "expression/simple",
    "gimmick/2B",
    "gimmick/circle only",
    "gimmick/ninja spinners",
    "gimmick/playfield constraint",
    "gimmick/slider only",
    "gimmick/storyboard",
    "jumps/linear",
    "jumps/sharp",
    "jumps/stamina",
    "jumps/wide",
    "meta/time signatures",
    "meta/variable timing",
    "reading/overlaps",
    "reading/perfect stacks",
    "reading/visually dense",
    "skillset/alt",
    "skillset/jumps",
    "skillset/precision",
    "skillset/streams",
    "sliders/complex slidershapes",
    "sliders/complex sv",
    "sliders/high sv",
    "sliders/low sv",
    "streams/bursts",
    "streams/cutstreams",
    "streams/flow aim",
    "streams/spaced streams",
    "streams/stamina",
    "style/grid snap",
    "style/symmetrical",
    "tech/aim control",
    "tech/finger control",
    "tech/slider tech",
]


ALL_TAGS: tuple[StyleTag, ...] = (
    "additions/keysounds",
    "expression/chaotic",
    "expression/playfield usage",
    "expression/simple",
    "gimmick/2B",
    "gimmick/circle only",
    "gimmick/ninja spinners",
    "gimmick/playfield constraint",
    "gimmick/slider only",
    "gimmick/storyboard",
    "jumps/linear",
    "jumps/sharp",
    "jumps/stamina",
    "jumps/wide",
    "meta/time signatures",
    "meta/variable timing",
    "reading/overlaps",
    "reading/perfect stacks",
    "reading/visually dense",
    "skillset/alt",
    "skillset/jumps",
    "skillset/precision",
    "skillset/streams",
    "sliders/complex slidershapes",
    "sliders/complex sv",
    "sliders/high sv",
    "sliders/low sv",
    "streams/bursts",
    "streams/cutstreams",
    "streams/flow aim",
    "streams/spaced streams",
    "streams/stamina",
    "style/grid snap",
    "style/symmetrical",
    "tech/aim control",
    "tech/finger control",
    "tech/slider tech",
)
